# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
  # name: topolvm-pvc
  # namespace: default
# spec:
  # accessModes:
  # - ReadWriteOnce
  # resources:
    # requests:
      # storage: 1Gi
  # storageClassName: topolvm-provisioner
# ---
# apiVersion: v1
# kind: Pod
# metadata:
  # name: my-pod
  # namespace: default
  # labels:
    # app.kubernetes.io/name: my-pod
    # app: example
# spec:
  # containers:
  # - name: pause
    # image: registry.k8s.io/pause
    # volumeMounts:
    # - mountPath: /test1
      # name: my-volume
  # volumes:
  # - name: my-volume
    # persistentVolumeClaim:
      # claimName: topolvm-pvc
# ---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-ephemeral
  namespace: default
  labels:
    app.kubernetes.io/name: my-pod-ephemeral
    app: example
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause
    volumeMounts:
    - mountPath: /test1
      name: my-volume
  volumes:
  - name: my-volume
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: topolvm-provisioner