name: Build and Deploy k4all

on:
  # schedule:
  #   - cron: "40 4 * * 1" # Runs at 4:40 UTC every Monday
  pull_request:
    branches:
      - image-based
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  push:
    branches:
      - image-based
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Brief description of changes in this build'
        required: false

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: k4all
  K4ALL_VERSION: testing
  ARCH: x86_64
  VARIANT: CoreOS
  ISO_NAME: k4all-${{ github.ref_name }}-${{ env.K4ALL_VERSION }}.iso

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    name: Build and Push Fedora CoreOS Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  build-iso:
    name: Build ISO
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build ISO
        uses: JasonN3/build-container-installer@v1.2.3
        with:
          arch: ${{ env.ARCH }}
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          image_tag: ${{ github.ref_name }}
          version: ${{ env.K4ALL_VERSION }}
          variant: ${{ env.VARIANT }}
          iso_name: ${{ env.ISO_NAME }}

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: ${{ env.ISO_NAME }}